# Generated by Django 6.0.2 on 2026-03-19 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="uploads/%Y/%m/%d"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
